
// generated by JavascriptGenerator version 0.1

function TestSample1(){
}

// dummy for prototype for netscape
new TestSample1();

TestSample1.prototype = new QHsm();

TestSample1.prototype.initialiseStateMachine = function(){
    this.initialiseState(this.s_StateX)
};


TestSample1.prototype.s_StateX = function(ev){
    if (ev.QSignal == QSignals.Entry) {
        this.enterStateX();
    } else if (ev.QSignal == QSignals.Exit) {
        this.exitStateX();
    } else if (ev.QSignal == QSignals.Init){
        this.initialiseState(this.s_State0);
    } else {
        return this._TopState;
    }
    return null;
}

TestSample1.prototype.s_State0 = function(ev){
    if (ev.QSignal == "Bye") {
        ;
        this.transitionTo(this.s_State1);
    } else if (ev.QSignal == "Hello") {
        if (this.Ok(ev)) {
            this.sayHello3();
            this.transitionTo(this.s_State0);
        } else {
            this.sayHello1();
            this.transitionTo(this.s_State1);
        }
    } else if (ev.QSignal == QSignals.Entry) {
        this.enterState0();
    } else if (ev.QSignal == QSignals.Exit) {
        this.exitState0();
    } else {
        return this.s_StateX;
    }
    return null;
}

TestSample1.prototype.s_State1 = function(ev){
    if (ev.QSignal == "Hello") {
        this.sayHello2();
        this.transitionTo(this.s_State0);
    } else if (ev.QSignal == QSignals.Entry) {
        this.enterState1();
    } else if (ev.QSignal == QSignals.Exit) {
        this.exitState1();
    } else {
        return this._TopState;
    }
    return null;
}

TestSample1.prototype.getNameOfStateMethod = function (stateMethod){
    if(stateMethod == this.s_StateX){
        return "StateX";
    }
    if(stateMethod == this.s_State0){
        return "State0";
    }
    if(stateMethod == this.s_State1){
        return "State1";
    }
    return QHsm.getNameOfStateMethod.call(this, stateMethod);
}

//end of TestSample1

